package by.epam.javatraining.restautant.command;

public enum CommandName {

    REGISTRATION,
    SIGN_IN,
    REDIRECT_TO_START_PAGE,
    ADD_TO_CART,
    LOGOUT,
    PROFILE,
    CREATE_ORDER,
    CONFIRM_ORDER,
    VIEW_USER_ORDERS,
    VIEW_ADMIN_PROFILE,
    VIEW_UNCONFIRMED_ORDERS,
    PROCESS_USER_ORDER,
    VIEW_ALL_USERS_ORDERS,
    VIEW_ALL_USERS,
    ENTER_FIND_USER_PAGE,
    ENTER_FIND_ORDER_PAGE,
    VIEW_ORDER_INFO,
    DELETE_ORDER,
    VIEW_USER_ORDERS_BY_ADMIN,
    DELETE_USER_ORDER_BY_ADMIN_INFO_PAGE,
    DELETE_USER,
    FIND_USER_BY_ID,
    FIND_USER_BY_LOGIN,
    FIND_USER_BY_EMAIL,
    DELETE_USER_BY_ID_SEARCH_PAGE,
    PROCESS_USER_ORDER_ON_SEARCH_PAGE,
    FIND_ORDER_BY_ID,
    FIND_ORDER_BY_USER_ID,
    DELETE_ORDER_ON_SEARCH_PAGE;
}
